// src/window/Config/pages/About/index.jsx
import { Divider, Button } from '@nextui-org/react';
import { useTranslation } from 'react-i18next';
import { open } from '@tauri-apps/plugin-shell';
import { BsGithub } from 'react-icons/bs';
import React from 'react';

import { appVersion } from '../../../../utils/env';

const GITHUB_URL = 'https://github.com/NIyueeE/pan-desktop';

export default function About() {
    const { t } = useTranslation();

    return (
        <div className='h-full w-full py-[80px] px-[100px]'>
            <img
                src='icon.png'
                className='mx-auto h-[100px] mb-[5px]'
                draggable={false}
            />
            <div className='content-center'>
                <h1 className='font-bold text-2xl text-center'>Pan</h1>
                <p className='text-center text-sm text-gray-500 mb-[5px]'>{appVersion}</p>
                <Divider />
                <p className='text-center text-sm text-gray-500 my-[15px] px-[20px]'>{t('config.about.intro')}</p>
                <Divider />
                <div className='flex justify-center'>
                    <Button
                        variant='light'
                        className='my-[5px]'
                        size='sm'
                        startContent={<BsGithub />}
                        onPress={() => {
                            open(GITHUB_URL);
                        }}
                    >
                        {t('config.about.github')}
                    </Button>
                </div>
            </div>
        </div>
    );
}

// src/windows/config/pages/About.svelte
<script lang="ts">
    import { open } from '@tauri-apps/plugin-shell';

    import { t } from '../../../lib/i18n/i18n.svelte';
    import { appEnv } from '../../../lib/utils/env.svelte';

    const GITHUB_URL = 'https://github.com/NIyueeE/pan-desktop';
</script>

<div class="flex h-full w-full flex-col items-center justify-center px-[100px] py-[80px]">
    <img src="/icon.png" alt="pan logo" class="mb-[5px] h-[100px]" draggable="false" />
    <h1 class="text-center text-2xl font-bold">Pan</h1>
    <p class="mb-[5px] text-center text-sm text-default-400">{appEnv.appVersion}</p>
    <div class="my-[15px] h-px w-full bg-divider"></div>
    <p class="my-[15px] px-[20px] text-center text-sm text-default-400">{t('config.about.intro')}</p>
    <div class="h-px w-full bg-divider"></div>
    <button
        type="button"
        class="my-[10px] flex items-center gap-2 rounded-md px-3 py-1.5 text-sm text-default-400 hover:bg-content2 hover:text-foreground"
        onclick={() => void open(GITHUB_URL)}
    >
        <!-- GitHub mark (brand icons were removed from lucide) -->
        <svg class="size-[16px]" viewBox="0 0 16 16" fill="currentColor" aria-hidden="true">
            <path
                d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27s1.36.09 2 .27c1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.01 8.01 0 0 0 16 8c0-4.42-3.58-8-8-8Z"
            />
        </svg>
        {t('config.about.github')}
    </button>
</div>
