// src/window/Config/pages/Backup/index.jsx
import { useEffect, useState } from 'react';
import { invoke } from '@tauri-apps/api/core';
import { Button, Card, CardBody, Input, Switch } from '@nextui-org/react';
import toast, { Toaster } from 'react-hot-toast';
import { useTranslation } from 'react-i18next';

import { useConfig, useToastStyle } from '../../../../hooks';
import { store } from '../../../../utils/store';
import {
    testConnection,
    uploadBackup,
    downloadBackup,
    applyBackup,
    DEFAULT_BACKUP_FILENAME,
} from '../../../../utils/webdav';

export default function Backup() {
    const [busy, setBusy] = useState(false);
    const [lastSynced, setLastSynced] = useState(null);
    const [webdavUrl, setWebdavUrl] = useConfig('webdav_url', '');
    const [webdavUsername, setWebdavUsername] = useConfig('webdav_username', '');
    const [webdavPassword, setWebdavPassword] = useConfig('webdav_password', '');
    const [webdavFilename, setWebdavFilename] = useConfig('webdav_filename', DEFAULT_BACKUP_FILENAME);
    const [webdavAutoSync, setWebdavAutoSync] = useConfig('webdav_auto_sync', false);
    const { t } = useTranslation();
    const toastStyle = useToastStyle();

    useEffect(() => {
        store.get('webdav_last_sync').then((v) => {
            if (v) {
                setLastSynced(new Date(v).toLocaleString());
            }
        });
    }, []);

    const ready = () => webdavUrl !== null && webdavUsername !== null && webdavPassword !== null;

    const showResult = (promise, successMessage) => {
        setBusy(true);
        promise
            .then(() => {
                toast.success(successMessage, { duration: 2000, style: toastStyle });
            })
            .catch((e) => {
                toast.error(String(e), { duration: 3000, style: toastStyle });
            })
            .finally(() => setBusy(false));
    };

    const markSynced = async () => {
        const now = Date.now();
        await store.set('webdav_last_sync', now);
        await store.save();
        setLastSynced(new Date(now).toLocaleString());
    };

    const onTest = () => {
        if (!ready()) {
            return;
        }
        showResult(testConnection(webdavUrl, webdavUsername, webdavPassword), t('config.backup.test_success'));
    };

    const onBackup = () => {
        if (!ready()) {
            return;
        }
        showResult(
            (async () => {
                await uploadBackup(store, webdavUrl, webdavUsername, webdavPassword, webdavFilename);
                await markSynced();
                await invoke('reload_store').catch(() => {});
            })(),
            t('config.backup.backup_success')
        );
    };

    const onRestore = () => {
        if (!ready()) {
            return;
        }
        // Restoring overwrites every local setting — require explicit consent.
        if (!window.confirm(t('config.backup.restore_confirm'))) {
            return;
        }
        showResult(
            (async () => {
                const payload = await downloadBackup(webdavUrl, webdavUsername, webdavPassword, webdavFilename);
                await applyBackup(store, payload);
                await invoke('reload_store');
                await markSynced();
            })(),
            t('config.backup.load_success')
        );
    };

    return (
        <>
            <Toaster />
            <Card className='mb-[10px]'>
                <CardBody className='flex flex-col gap-[10px]'>
                    <div className='config-item'>
                        <h3>{t('config.backup.webdav_url')}</h3>
                        {webdavUrl !== null && (
                            <Input
                                variant='bordered'
                                placeholder='https://dav.example.com/dav/'
                                value={webdavUrl}
                                onValueChange={setWebdavUrl}
                                className='max-w-[420px]'
                                isDisabled={busy}
                            />
                        )}
                    </div>
                    <div className='config-item'>
                        <h3>{t('config.backup.username')}</h3>
                        {webdavUsername !== null && (
                            <Input
                                variant='bordered'
                                value={webdavUsername}
                                onValueChange={setWebdavUsername}
                                className='max-w-[260px]'
                                isDisabled={busy}
                            />
                        )}
                    </div>
                    <div className='config-item'>
                        <h3>{t('config.backup.password')}</h3>
                        {webdavPassword !== null && (
                            <Input
                                type='password'
                                variant='bordered'
                                value={webdavPassword}
                                onValueChange={setWebdavPassword}
                                className='max-w-[260px]'
                                isDisabled={busy}
                            />
                        )}
                    </div>
                    <div className='config-item'>
                        <h3>{t('config.backup.filename')}</h3>
                        {webdavFilename !== null && (
                            <Input
                                variant='bordered'
                                value={webdavFilename}
                                onValueChange={setWebdavFilename}
                                className='max-w-[260px]'
                                isDisabled={busy}
                            />
                        )}
                    </div>
                    <Button
                        variant='bordered'
                        className='max-w-[200px]'
                        isDisabled={!ready()}
                        isLoading={busy}
                        onPress={onTest}
                    >
                        {t('config.backup.test')}
                    </Button>
                </CardBody>
            </Card>
            <Card className='mb-[10px]'>
                <CardBody className='flex flex-col gap-[10px]'>
                    <div className='config-item'>
                        <h3>{t('config.backup.auto_sync')}</h3>
                        {webdavAutoSync !== null && (
                            <Switch
                                isSelected={webdavAutoSync}
                                isDisabled={busy || !webdavUrl}
                                onValueChange={(v) => {
                                    setWebdavAutoSync(v);
                                    if (v && !webdavUrl) {
                                        toast.error(t('config.backup.need_url'), {
                                            duration: 3000,
                                            style: toastStyle,
                                        });
                                    }
                                }}
                            />
                        )}
                    </div>
                    <p className='text-xs text-default-500'>{t('config.backup.auto_sync_desc')}</p>
                    {lastSynced !== null && (
                        <p className='text-xs text-default-500'>
                            {t('config.backup.last_synced')}
                            {lastSynced}
                        </p>
                    )}
                </CardBody>
            </Card>
            <Card>
                <CardBody className='flex flex-row justify-start gap-[10px]'>
                    <Button
                        color='primary'
                        className='max-w-[200px]'
                        isDisabled={!ready()}
                        isLoading={busy}
                        onPress={onBackup}
                    >
                        {t('config.backup.backup')}
                    </Button>
                    <Button
                        color='warning'
                        variant='bordered'
                        className='max-w-[200px]'
                        isDisabled={!ready()}
                        isLoading={busy}
                        onPress={onRestore}
                    >
                        {t('config.backup.restore')}
                    </Button>
                </CardBody>
            </Card>
        </>
    );
}

// src/windows/config/pages/Backup.svelte
<script lang="ts">
    import { onMount } from 'svelte';
    import { toast, Toaster } from 'svelte-sonner';

    import { cfg, getStoreInstance, setConfig, trackConfigKeys, writeThrough } from '../../../lib/config/store.svelte';
    import { reloadStore } from '../../../lib/ipc/commands';
    import { t } from '../../../lib/i18n/i18n.svelte';
    import { applyBackup, downloadBackup, testConnection, uploadBackup } from '../../../lib/utils/webdav';
    import { themeState } from '../../../lib/utils/theme.svelte';
    import PSwitch from '../../../lib/ui/PSwitch.svelte';
    import Section from '../../../lib/ui/Section.svelte';
    import SettingRow from '../../../lib/ui/SettingRow.svelte';
    import TextField from '../../../lib/ui/TextField.svelte';

    void trackConfigKeys(['webdav_url', 'webdav_username', 'webdav_password', 'webdav_filename', 'webdav_auto_sync']);

    let busy = $state(false);
    let lastSynced = $state<string | null>(null);

    onMount(() => {
        const store = getStoreInstance();
        if (!store) {
            return;
        }
        void store.get('webdav_last_sync').then((value) => {
            if (value) {
                lastSynced = new Date(Number(value)).toLocaleString();
            }
        });
    });

    const ready = $derived(cfg('webdav_url') !== '' && cfg('webdav_username') !== '' && cfg('webdav_password') !== '');

    async function markSynced(): Promise<void> {
        const now = Date.now();
        await writeThrough('webdav_last_sync', now);
        lastSynced = new Date(now).toLocaleString();
    }

    function run(promise: Promise<void>, successMessage: string): void {
        busy = true;
        promise
            .then(() => {
                toast.success(successMessage, { duration: 2000 });
            })
            .catch((e: unknown) => {
                toast.error(String(e), { duration: 3000 });
            })
            .finally(() => (busy = false));
    }

    const credentials = () => ({
        url: cfg('webdav_url'),
        username: cfg('webdav_username'),
        password: cfg('webdav_password'),
        filename: cfg('webdav_filename'),
    });

    function onTest(): void {
        if (!ready) {
            return;
        }
        const { url, username, password } = credentials();
        run(
            testConnection(url, username, password).then(() => undefined),
            t('config.backup.test_success')
        );
    }

    function onBackup(): void {
        if (!ready) {
            return;
        }
        const { url, username, password, filename } = credentials();
        const store = getStoreInstance();
        if (!store) {
            return;
        }
        run(
            (async () => {
                await uploadBackup(store, url, username, password, filename);
                await markSynced();
                await reloadStore();
            })(),
            t('config.backup.backup_success')
        );
    }

    function onRestore(): void {
        if (!ready) {
            return;
        }
        const { url, username, password, filename } = credentials();
        const store = getStoreInstance();
        if (!store) {
            return;
        }
        // Restoring overwrites every local setting — require explicit consent.
        if (!window.confirm(t('config.backup.restore_confirm'))) {
            return;
        }
        run(
            (async () => {
                const payload = await downloadBackup(url, username, password, filename);
                await applyBackup(store, payload);
                await reloadStore();
                await markSynced();
            })(),
            t('config.backup.load_success')
        );
    }
</script>

<Toaster theme={themeState.resolved} position="bottom-right" richColors />

<Section>
    <SettingRow label={t('config.backup.webdav_url')}>
        <TextField
            value={cfg('webdav_url')}
            placeholder="https://dav.example.com/dav/"
            class="w-[320px]"
            disabled={busy}
            onValueChange={(v) => void writeThrough('webdav_url', v)}
        />
    </SettingRow>
    <SettingRow label={t('config.backup.username')}>
        <TextField
            value={cfg('webdav_username')}
            class="w-[220px]"
            disabled={busy}
            onValueChange={(v) => void writeThrough('webdav_username', v)}
        />
    </SettingRow>
    <SettingRow label={t('config.backup.password')}>
        <TextField
            type="password"
            value={cfg('webdav_password')}
            class="w-[220px]"
            disabled={busy}
            onValueChange={(v) => void writeThrough('webdav_password', v)}
        />
    </SettingRow>
    <SettingRow label={t('config.backup.filename')}>
        <TextField
            value={cfg('webdav_filename')}
            class="w-[220px]"
            disabled={busy}
            onValueChange={(v) => void writeThrough('webdav_filename', v)}
        />
    </SettingRow>
    <button
        type="button"
        class="h-[32px] rounded-md border border-default-200 px-4 text-sm hover:bg-content2 disabled:opacity-50"
        disabled={!ready || busy}
        onclick={onTest}
    >
        {t('config.backup.test')}
    </button>
</Section>

<Section>
    <SettingRow label={t('config.backup.auto_sync')}>
        <PSwitch
            checked={cfg('webdav_auto_sync')}
            disabled={!cfg('webdav_url')}
            onCheckedChange={(v) => setConfig('webdav_auto_sync', v)}
        />
    </SettingRow>
    <p class="mb-2 text-xs text-default-400">{t('config.backup.auto_sync_desc')}</p>
    {#if lastSynced !== null}
        <p class="text-xs text-default-400">{t('config.backup.last_synced')}{lastSynced}</p>
    {/if}
</Section>

<Section>
    <div class="flex justify-start gap-[10px]">
        <button
            type="button"
            class="h-[32px] rounded-md bg-primary px-4 text-sm text-primary-foreground hover:opacity-90 disabled:opacity-50"
            disabled={!ready || busy}
            onclick={onBackup}
        >
            {t('config.backup.backup')}
        </button>
        <button
            type="button"
            class="h-[32px] rounded-md border border-danger/50 px-4 text-sm text-danger hover:bg-danger/10 disabled:opacity-50"
            disabled={!ready || busy}
            onclick={onRestore}
        >
            {t('config.backup.restore')}
        </button>
    </div>
</Section>
